#pragma config(Motor,  port1,           RightFrontDrive, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RightBackDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LeftFrontDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LeftBackDrive, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Necessary File For Vex Competition
#include "Vex_Competition_Includes.c"


#include "Drive.c"
#include "Intake.c"
#include "Shooter.c"
#include "Elevator.c"

#include "LCD.c"


#include "Lift.c"

#include "LCDTask.c"

#include "Auto.c"

#include "MiscFunctions.c"

#define UPDATECONTROLLER

#define LOGENCODERS
#define LOGDRIVEPID
#define LOGSHOOTERPID

struct LCD LCD;
// Ran when you turn ON Robot, I opt not to use this
void pre_auton() {

}

// Ran in Auto
task autonomous() {
	// Reset Encoders and then run the begin auto method found in AUTO.c
	resetEn();
	startauton();
	stopDrive();
}

//Ran in Teleop
task usercontrol() {
	LCDinit();
	//Clear LCD and Reset Sensors, then begin teleop
	clearLCDLine(0);
	startTask( LCD );

	resetEn();
	resetGyro();

	//Start the tasks that control each aspect of the robot
	startTask( driveTask );
	startTask( intakeTask );
	startTask( elevatorTask );
	startTask( shooterTask);
	startTask( liftTask );

	while(true) {
		if (vexRT[Btn8L]) {
			shiftToLiftMode();
		}else if (vexRT[Btn8R]) {
			shiftToBallMode();
		}
	}
}
